// fonts
import { config, dom, library } from "@fortawesome/fontawesome-svg-core";

import {
  faTimes,
  faTimesCircle,
  faPlus,
  faBook,
  faFlask,
  faBox,
  faSatelliteDish,
  faClipboard,
  faCopy,
  faClone,
  faAnglesRight,
  faGears,
  faCloudUploadAlt,
  faBuildingShield,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faRightFromBracket,
  faRightToBracket,
  faSquareCaretDown,
  faRotateRight,
  faHistory,
  faSearch,
  faUpRightFromSquare,
  faIdBadge,
  faUserTag,
  faTags,
  faFileLines,
  faKey,
  faLayerGroup,
  faProjectDiagram,
  faNetworkWired,
  faHdd,
  faUsers,
  faServer,
  faDatabase,
  faSlash,
  faEllipsisVertical,
  faCircleQuestion,
} from "@fortawesome/free-solid-svg-icons";

import {
  faUbuntu,
  faDebian,
  faLinux,
  faWindows,
} from "@fortawesome/free-brands-svg-icons";

// Make sure this is before any other `fontawesome` API calls
config.autoAddCss = false;

library.add(
  faTimes,
  faTimesCircle,
  faPlus,
  faBook,
  faFlask,
  faBox,
  faSatelliteDish,
  faClipboard,
  faCopy,
  faClone,
  faAnglesRight,
  faGears,
  faCloudUploadAlt,
  faBuildingShield,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faRightFromBracket,
  faRightToBracket,
  faSquareCaretDown,
  faRotateRight,
  faHistory,
  faSearch,
  faUpRightFromSquare,
  faIdBadge,
  faUserTag,
  faTags,
  faFileLines,
  faKey,
  faLayerGroup,
  faProjectDiagram,
  faNetworkWired,
  faHdd,
  faUsers,
  faUbuntu,
  faLinux,
  faDebian,
  faWindows,
  faServer,
  faDatabase,
  faSlash,
  faEllipsisVertical,
  faCircleQuestion
);

dom.watch();
